### ISSUE TITLE
Roomba 890 Discovery

### ISSUE THREAD

**Issue by fpagliughi** [cecton/roomba#1]
Just for reference, this is the discovery info for my Roomba 890:
```
{
  "ver": "3",
  "hostname": "Roomba-3176C00861529850",
  "robotname": "Jeff",
  "ip": "192.168.1.251",
  "mac": "D0:C5:D3:8F:49:32",
  "sw": "3.2.47",
  "sku": "R890020",
  "nc": 0,
  "proto": "mqtt",
  "cap": {
    "ota": 1,
    "eco": 1,
    "svcConf": 1
  }
}
```
Note that it doesn't have an ID field, but I believe the ID is part of the hostname after the dash. I believe the hostname can be "Roomba-XXX" or "iRobot-XXX" on some models.

**Comment by cecton** [comment]
Noted
